### ISSUE TITLE
[feature] post inherits common attributes

### ISSUE THREAD

**Issue by j-d-carmichael** [acrontum/boats-cli#20]
```
➜  prompt-template git:(main) ✗ tree -l
.
├── baseAttributes.yml
├── models.yml
├── model.yml
├── patch.yml
└── post.yml
```
Typically, I use this pattern... the base attributes contain the common attributes that are typically required in post/put/model

In the `post.yml` I would then have:
```
allOf:
  - $ref: ./baseAttributes.yml
  - ... optional additional object data if needed
```

In the `model.yml`, I would then house the things the user does not alter:
```
allOf:
  - $ref: ./baseAttributes.yml
  - type: object
    properties:
      createdAt:
        type: string
        format: date-time
      .... etc etc
```

finally in the `baseAttributes.yml`, I add the meat of the object that usually contains common things eg:
```
type: object
required:
  - name
  - userPrompt
  - systemPrompt
properties:
  name:
    type: string
  userPrompt:
    type: string
  systemPrompt:
    type: string
```

I would not know how, but it would be great to be able to define the boiler plate boats-cli outputs...
