### ISSUE TITLE
[feature] quote or not to quote - cli arg?

### ISSUE THREAD

**Issue by j-d-carmichael** [acrontum/boats-cli#21]
```
type: "object"
required:
  - "meta"
  - "data"
properties:
  meta:
    $ref: "../pagination/model.yml"
  data:
    type: "array"
    items:
      $ref: "./model.yml"
```
or 
```
type: "object"
required:
  - meta
  - data
properties:
  meta:
    $ref: ../pagination/model.yml
  data:
    type: array
    items:
      $ref: ./model.yml
```

Personally, i have always gone for the latter... and right now with the this cli I have to go in and do a mass replace 

I guess this comes from here: https://github.com/acrontum/boats-cli/blob/main/src/lib.ts#L87

Would be great to be able to control the " there.. maybe as an rc file and/or a cli arg?
